akt_direkt_proxy/views/startpage.py
"""User interface of the example application."""

import flask

__copyright__ = """

    Copyright 2018 Lantmäteriet

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

"""

bp = flask.Blueprint("user_interface", __name__, url_prefix="/")


@bp.route("/")
@bp.route("/index.html")
def index():
    """Generate the startpage with form for generation dossier URLs."""
    test_result = flask.current_app.client.test_connection()
    return flask.render_template("startpage.html", test_result=test_result)


@bp.route("/djvu_url")
def djvu_url():
    """Generate a dossier URL."""
    archive = flask.request.args.get("archive").strip()
    document_id = flask.request.args.get("document_id").strip()
    djvu_url = flask.url_for(
        "proxy.get_djvu", archive=archive, id=document_id, _external=True
    )
    djvu_url_djvu_on_error = flask.url_for(
        "proxy.get_djvu_djvu_on_error", archive=archive, id=document_id, _external=True
    )
    return flask.render_template(
        "djvu_url.html",
        djvu_url=djvu_url,
        djvu_url_djvu_on_error=djvu_url_djvu_on_error,
    )


@bp.route("/update_token")
def get_update_token():
    """Force a oauth token update, only used for testing.

    to test this service use:
        djview "http://localhost:5000/update_token"
    """
    flask.current_app.client.update_token()
    return "ok"


@bp.route("/break_token")
def get_break_token():
    """Break the cached oauth token, only used for testing error handling.

    to test this service use:
        djview "http://localhost:5000/break_token"
    """
    flask.current_app.client.oauth.token = []
    return "ok"

akt_direkt_proxy/templates/djvu_url.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Akt Direkt testklient</title>
</head>
<body>
    <h1>Url till specificerad akt</h1>

    Om du har en DjVU-plugin eller en separad DjVU-visare installerad kan du titta på akten genom att klicka på någon av dessa länkar.
    <br/><br/>
    Med normal felhantering: <br/><a href={{ djvu_url }}>{{ djvu_url }}</a>
    <br/><br/>
    DjVU baserad felhantering: <br/><a href={{ djvu_url_djvu_on_error }}>{{ djvu_url_djvu_on_error }}</a>
    <br/><br/>
    <br/><br/>
    <br/><br/>
    Det rekommenderade sättet att titta på DjVU med V4 APIet är att låta webbläsaren öppna bilden i en separat DjVU-visare som <a href="http://djvu.sourceforge.net/djview4.html">djview4</a>.
    <br/>
    Med lite mer arbete och med minimal funktionalitet kan den rena HTML5 DjVU-visaren <a href="https://github.com/mateusz-matela/djvu-html5/">djvu-html5</a> användas.
    <br/><br/>
    Tidigare krävdes att du hade en NPAPI DjVU-plugin installerad för att det skulle gå att öppna en djvu länk direkt i webbläsaren.
    Om du har en DjVU-plugin installerad så kan du fortsätta använda den som tidigare om du så önskar. <br/>
    <br/>
    Det gick tidigare inte att att spara ner filen som länkas och sedan öppna den men det fungerar med API V4. <br/>
    <br/>
    Man kan välja mellan att få fel rapporterade på två sätt, antingen som HTTP felkoder i kombination med JSON baserat felmeddelande eller som DjVU bilder. <br/>
    DjVU baserade fel är för lösningar som NPAPI plugins som inte presenterar felmeddelanden på ett vettigt sätt. <br/>
    API V3 gav alltid felmeddelanden i DjVU format. <br/>
    <br/>

</body>
</html>

akt_direkt_proxy/templates/index_url.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Akt Direkt testklient</title>
</head>
<body>
    <h1>Url till specificerad akt</h1>

    Om du har en DjVU-plugin eller en separad DjVU-visare installerad kan du titta på akten genom att klicka på länken nedan.
    <br/><br/>
    Det rekommenderade sättet att titta på DjVU med V4 APIet är att låta webbläsaren öppna bilden i en separat DjVU-visare som <a href="http://djvu.sourceforge.net/djview4.html">djview4</a>.
    <br/>
    Med lite mer arbete och med minimal funktionalitet kan den rena HTML5 DjVU-visaren <a href="https://github.com/mateusz-matela/djvu-html5/">djvu-html5</a> användas.
    <br/><br/>
    Tidigare krävdes att du hade en NPAPI DjVU-plugin installerad för att det skulle gå att öppna en djvu länk direkt i webbläsaren.
    Om du har en DjVU-plugin installerad så kan du fortsätta använda den som tidigare om du så önskar. <br/>
    <br/>
    Det gick tidigare inte att att spara ner filen som länkas och sedan öppna den men det fungerar med API V4. <br/>
    Man kan välja mellan att få fel rapporterade på två sätt, antingen som HTTP felkoder i kombination med JSON baserat felmeddelande eller som DjVU bilder. <br/>
    DjVU baserade fel är för lösningar som NPAPI plugins som inte presenterar felmeddelanden på ett vettigt sätt. <br/>
    API V3 gav alltid felmeddelanden i DjVU format. <br/>
    <br/>
    Med normal felhantering: <a href={{ index_url }}>{{ index_url }}</a>
    <br/><br/>
    DjVU baserad felhantering: <a href={{ index_url_djvu_on_error }}>{{ index_url_djvu_on_error }}</a>

</body>
</html>

akt_direkt_proxy/templates/startpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Akt Direkt testklient</title>
</head>
<body>
    <ul id="navigation">
    {% for item in navigation %}
        <li><a href="{{ item.href }}">{{ item.caption }}</a></li>
    {% endfor %}
    </ul>

    <h1>Akt Direkt testklient</h1>

    Test av kommunikationen med Akt Direkt {{ 'lyckades' if test_result else '<h2>misslyckades</h2>'|safe}}.
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>

    <h2>Generera url för användning med djview eller annan DjVU visare</h2>

    <form action="{{ url_for('user_interface.djvu_url') }}" method="get"> <table><tbody>
        <tr><td>Arkiv:</td><td><input id="archive" name="archive" size="4" tabindex="1" type="text" value="" /> ex. 21 eller k21g</td></tr>
        <tr><td>Aktbeteckning:</td><td><input id="document_id" name="document_id" size="80" tabindex="2" type="text" value="" /> ex. 2180k-10/11</td></tr>
        <tr><td></td><td><input id="submit" name="submit" tabindex="3" type="submit" value="Generera URL" /></td></tr>
    </tbody> </table> </form>

    {# a comment #}
</body>
</html>